name: MSBuild

on:
#   workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: ./offt.sln

permissions:
  contents: read

jobs:
  build:

    runs-on: windows-latest

    strategy:
      matrix:
        include:
        
          - configuration: "Release"
            platform: "x86"
            platform_path: "./"

          - configuration: "Release"
            platform: "x64"
            platform_path: "./x64/"

    steps:

    - uses: actions/checkout@v3

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.1

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m /p:Configuration=${{matrix.configuration}} /p:Platform=${{matrix.platform}} ${{env.SOLUTION_FILE_PATH}}
      
    - name: Run self-test
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: ${{matrix.platform_path}}${{matrix.configuration}}/benchmark.exe --self-test
